version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:3000"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
